### 🧪 Registro de usuário
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "REST Client",
  "email": "rest@example.com",
  "phone": "11999999999",
  "password": "123456",
  "confirmPassword": "123456"
}

### 🔑 Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "emailNaoCadastrado@example.com",
  "password": "123456"
}

### 🚪 Logout
POST http://localhost:3000/api/logout

### Calcular Pontos da Semana
POST http://localhost:3000/api/scoring/calculate
Content-Type: application/json

{
  "seasonId": 2025,
  "weekNumber": 1
}

### Ingest Games ESPN
POST http://localhost:3000/api/ingest-games
Content-Type: application/json

{
  "week": 2
}